### PR TITLE
FRI PCS adjust indices based on the "global" max height

### LINKED ISSUE #250: Multi batch opening with different max heights in FRI
When attempting to make a `open_multi_batches` call with batches that have different maximum heights, the code panics for accessing invalid rows. 

Here is an example of a test failure:
https://github.com/Plonky3/Plonky3/blob/multi-batch-fail/fri/tests/pcs.rs#L108

In the context of FRI, the problem seems to be that the shifts of degrees on the tree assume the `log_max_degree` is the same for all batches in https://github.com/Plonky3/Plonky3/blob/main/fri/src/two_adic_pcs.rs#L299:
```rust
        let query_openings = query_indices
            .into_iter()
            .map(|index| {
                prover_data_and_points
                    .iter()
                    .map(|(data, _)| {
                        let (opened_values, opening_proof) = self.mmcs.open_batch(index, data);
                        BatchOpening {
                            opened_values,
                            opening_proof,
                        }
                    })
                    .collect()
            })
            .collect();
```
That is because `query_indices` are computed with the maximum height of all batches as basis, whereas the shifts in `open_batch`, which are computed by the following code:
```rust
        let openings = prover_data
            .leaves
            .iter()
            .map(|matrix| {
                let log2_height = log2_ceil_usize(matrix.height());
                let bits_reduced = log_max_height - log2_height;
                let reduced_index = index >> bits_reduced;
                matrix.row(reduced_index).collect()
            })
            .collect_vec();
 ```
are computing the shift with respect to the maximum height of that batch. This ends up with overflow in the rows if the `max_height_for batch < max_height_on_all_batches`.

I have also checked an earlier commit of FRI, and had the same failure, so this behavior did not originate from recent fixes. 

Is this the intended behavior of `open_multi_batches`? If so, we should probably add some comments in the trait as the errors were a little confusing to debug. If it's not the intended behavior, happy to explore a fix (some naive fixes I tried didn't work).

### PR DESCRIPTION
**Pull request by dlubarov**
"Global" in the sense that it's the max for all FRI inputs, not just for all matrices under a certain commitment.

Fixes #250.

### CODE REVIEW

**Comment by dlubarov** [comment]
I was working on a test, but it's rather long, and not quite compiling as I ran into a type inference issue. Maybe we can proceed without for now since #250 is pretty critical and SP1 acts as an integration test for it for now.

**Comment by tamirhemo** [comment]
Does adjusting this test like in the original issue could be enough for now?
https://github.com/Plonky3/Plonky3/blob/main/fri/tests/pcs.rs

**Comment by dlubarov** [comment]
@tamirhemo good point, forgot about that existing test, I'll adapt that one.

File: fri/src/two_adic_pcs.rs [hunk 1]
```diff
@@ -329,19 +334,27 @@ where
...
                 let mut alpha_pow = [Challenge::one(); 32];
+
                 for (batch_opening, (batch_commit, mats)) in izip!(query_opening, &rounds) {
-                    let batch_dims: Vec<Dimensions> = mats
+                    let batch_heights = mats
                         .iter()
-                        .map(|(domain, _)| Dimensions {
-                            // todo: mmcs doesn't really need width
-                            width: 0,
-                            height: domain.size(),
```
Comment (dlubarov) [inline fri/src/two_adic_pcs.rs:338]: I think this was a bug - we want to pass the MMCS the codeword length, but `domain.size()` is the dimension. It wasn't causing errors before since `FieldMerkleTreeMmcs` only uses heights for relative ordering.

File: fri/src/two_adic_pcs.rs [hunk 2]
```diff
@@ -272,8 +273,11 @@ where
                 rounds
                     .iter()
                     .map(|(data, _)| {
-                        // needs to recombine decomposed openings.. or something...
```
Comment (rjeli) [inline fri/src/two_adic_pcs.rs:275]: ugh, I need to be more explicit in my TODOs - I think this was referring to the unused API I had where it would automatically decompose polys with too high degree. so not relevant

**Review by rjeli — APPROVED** [review]
LGTM
