### PR TITLE
fix: reduce logging noise in batch-stark with multiple AIRs

### LINKED ISSUE #1247: `p3-batch-stark` logging gets noisy with multiple AIRs
The `p3-batch-stark` prover logic loops over all batched instances to go through the STARK protocol, effectively opacifying a bit the timing information in the logs, which are crucial for performance optimization. For instance, see below in a system with 6 AIR tables `RUST_LOG=info` mode:

<details><summary>Logging run</summary>
<p>

```bash
INFO     ┕━ prove_batch [ 6.92ms | 23.25% / 98.05% ]
INFO        ┝━ infer log of constraint degree [ 71.9µs | 1.02% ]
INFO        ┝━ infer log of constraint degree [ 8.79µs | 0.12% ]
INFO        ┝━ infer log of constraint degree [ 6.67µs | 0.09% ]
INFO        ┝━ infer log of constraint degree [ 101µs | 1.43% ]
INFO        ┝━ infer log of constraint degree [ 30.8µs | 0.44% ]
INFO        ┝━ infer log of constraint degree [ 497µs | 7.04% ]
INFO        ┝━ coset_lde_batch [ 1.71µs | 0.02% ] dims: 16x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 1.75µs | 0.02% ] dims: 4x8 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 875ns | 0.01% ] dims: 4x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 584ns | 0.01% ] dims: 48x1 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 500ns | 0.01% ] dims: 12x1 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 3.04µs | 0.04% ] dims: 301x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 958ns | 0.01% ] dims: 16x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 1.00µs | 0.01% ] dims: 4x8 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 666ns | 0.01% ] dims: 4x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 458ns | 0.01% ] dims: 48x1 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 459ns | 0.01% ] dims: 12x1 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 1.17µs | 0.02% ] dims: 28x4 | added_bits: 1
INFO        ┝━ compute quotient polynomial [ 17.0µs | 0.24% ]
INFO        ┝━ coset_lde_batch [ 1.58µs | 0.02% ] dims: 4x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 834ns | 0.01% ] dims: 4x4 | added_bits: 1
INFO        ┝━ compute quotient polynomial [ 11.3µs | 0.16% ]
INFO        ┝━ coset_lde_batch [ 2.08µs | 0.03% ] dims: 4x8 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 1.21µs | 0.02% ] dims: 4x8 | added_bits: 1
INFO        ┝━ compute quotient polynomial [ 7.21µs | 0.10% ]
INFO        ┝━ coset_lde_batch [ 625ns | 0.01% ] dims: 4x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 584ns | 0.01% ] dims: 4x4 | added_bits: 1
INFO        ┝━ compute quotient polynomial [ 15.7µs | 0.22% ]
INFO        ┝━ coset_lde_batch [ 875ns | 0.01% ] dims: 4x1 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 625ns | 0.01% ] dims: 4x1 | added_bits: 1
INFO        ┝━ compute quotient polynomial [ 7.33µs | 0.10% ]
INFO        ┝━ coset_lde_batch [ 542ns | 0.01% ] dims: 4x1 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 500ns | 0.01% ] dims: 4x1 | added_bits: 1
INFO        ┝━ compute quotient polynomial [ 38.9µs | 0.55% ]
INFO        ┝━ coset_lde_batch [ 875ns | 0.01% ] dims: 4x4 | added_bits: 1
INFO        ┝━ coset_lde_batch [ 667ns | 0.01% ] dims: 4x4 | added_bits: 1
INFO        ┝━ compute_inverse_denominators [ 3.83µs | 0.05% ]
INFO        ┝━ evaluate matrix [ 14.7µs | 0.18% / 0.21% ] dims: 16x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.67µs | 0.02% ]
INFO        ┝━ evaluate matrix [ 13.8µs | 0.18% / 0.20% ] dims: 16x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.08µs | 0.02% ]
INFO        ┝━ evaluate matrix [ 4.33µs | 0.05% / 0.06% ] dims: 4x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 792ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 4.12µs | 0.05% / 0.06% ] dims: 4x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 625ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 4.04µs | 0.05% / 0.06% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 500ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.92µs | 0.05% / 0.06% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 416ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 38.9µs | 0.53% / 0.55% ] dims: 48x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.79µs | 0.03% ]
INFO        ┝━ evaluate matrix [ 38.5µs | 0.53% / 0.54% ] dims: 48x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.25µs | 0.02% ]
INFO        ┝━ evaluate matrix [ 10.2µs | 0.14% / 0.14% ] dims: 12x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 625ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 10.2µs | 0.14% / 0.14% ] dims: 12x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 500ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 235µs | 3.25% / 3.33% ] dims: 301x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 5.12µs | 0.07% ]
INFO        ┝━ evaluate matrix [ 235µs | 3.26% / 3.33% ] dims: 301x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 4.75µs | 0.07% ]
INFO        ┝━ evaluate matrix [ 3.92µs | 0.05% / 0.06% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 458ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.92µs | 0.05% / 0.06% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 375ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 4.04µs | 0.05% / 0.06% ] dims: 4x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 500ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.96µs | 0.05% / 0.06% ] dims: 4x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 459ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 4.00µs | 0.05% / 0.06% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 417ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.79µs | 0.05% / 0.05% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 375ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.88µs | 0.05% / 0.05% ] dims: 4x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 417ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.88µs | 0.05% / 0.05% ] dims: 4x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 333ns | 0.00% ]
INFO        ┝━ evaluate matrix [ 3.83µs | 0.05% / 0.05% ] dims: 4x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 291ns | 0.00% ]
INFO        ┝━ evaluate matrix [ 3.75µs | 0.05% / 0.05% ] dims: 4x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 333ns | 0.00% ]
INFO        ┝━ evaluate matrix [ 3.83µs | 0.05% / 0.05% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 375ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.83µs | 0.05% / 0.05% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 375ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 7.17µs | 0.09% / 0.10% ] dims: 8x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 667ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 7.04µs | 0.09% / 0.10% ] dims: 8x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 584ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 2.58µs | 0.03% / 0.04% ] dims: 2x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 625ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 2.42µs | 0.03% / 0.03% ] dims: 2x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 458ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 2.38µs | 0.03% / 0.03% ] dims: 2x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 416ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 2.33µs | 0.03% / 0.03% ] dims: 2x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 417ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 13.2µs | 0.18% / 0.19% ] dims: 16x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 792ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 13.2µs | 0.18% / 0.19% ] dims: 16x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 791ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.88µs | 0.05% / 0.05% ] dims: 4x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 333ns | 0.00% ]
INFO        ┝━ evaluate matrix [ 3.83µs | 0.05% / 0.05% ] dims: 4x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 375ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 18.0µs | 0.24% / 0.26% ] dims: 23x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.04µs | 0.01% ]
INFO        ┝━ evaluate matrix [ 19.4µs | 0.26% / 0.27% ] dims: 23x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 916ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 13.3µs | 0.18% / 0.19% ] dims: 16x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 875ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 13.2µs | 0.18% / 0.19% ] dims: 16x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 791ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.96µs | 0.05% / 0.06% ] dims: 4x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 458ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 4.04µs | 0.05% / 0.06% ] dims: 4x16
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 542ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.92µs | 0.05% / 0.06% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 459ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 3.96µs | 0.05% / 0.06% ] dims: 4x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 500ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 37.5µs | 0.52% / 0.53% ] dims: 48x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.12µs | 0.02% ]
INFO        ┝━ evaluate matrix [ 37.5µs | 0.52% / 0.53% ] dims: 48x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.12µs | 0.02% ]
INFO        ┝━ evaluate matrix [ 10.1µs | 0.14% / 0.14% ] dims: 12x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 583ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 10.1µs | 0.13% / 0.14% ] dims: 12x2
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 625ns | 0.01% ]
INFO        ┝━ evaluate matrix [ 22.4µs | 0.30% / 0.32% ] dims: 28x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 1.04µs | 0.01% ]
INFO        ┝━ evaluate matrix [ 22.7µs | 0.31% / 0.32% ] dims: 28x8
INFO        │  ┕━ compute opened values with Lagrange interpolation [ 917ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 2.12µs | 0.02% / 0.03% ] dims: 16x8
INFO        │  ┕━ compress mat [ 625ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.83µs | 0.02% / 0.03% ] dims: 4x16
INFO        │  ┕━ compress mat [ 625ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.33µs | 0.01% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 333ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 2.00µs | 0.02% / 0.03% ] dims: 48x2
INFO        │  ┕━ compress mat [ 250ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.21µs | 0.01% / 0.02% ] dims: 12x2
INFO        │  ┕━ compress mat [ 208ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 10.2µs | 0.10% / 0.14% ] dims: 301x8
INFO        │  ┕━ compress mat [ 3.12µs | 0.04% ]
INFO        ┝━ reduce matrix quotient [ 1.17µs | 0.01% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 333ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.12µs | 0.01% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 333ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.25µs | 0.01% / 0.02% ] dims: 4x16
INFO        │  ┕━ compress mat [ 500ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.33µs | 0.01% / 0.02% ] dims: 4x16
INFO        │  ┕━ compress mat [ 500ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.12µs | 0.01% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 334ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.08µs | 0.01% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 291ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 917ns | 0.01% / 0.01% ] dims: 4x2
INFO        │  ┕━ compress mat [ 167ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 833ns | 0.01% / 0.01% ] dims: 4x2
INFO        │  ┕━ compress mat [ 166ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 875ns | 0.01% / 0.01% ] dims: 4x2
INFO        │  ┕━ compress mat [ 167ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 792ns | 0.01% / 0.01% ] dims: 4x2
INFO        │  ┕━ compress mat [ 125ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.08µs | 0.01% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 334ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.12µs | 0.01% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 333ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.54µs | 0.02% / 0.02% ] dims: 8x8
INFO        │  ┕━ compress mat [ 333ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.71µs | 0.02% / 0.02% ] dims: 2x16
INFO        │  ┕━ compress mat [ 583ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.38µs | 0.01% / 0.02% ] dims: 2x8
INFO        │  ┕━ compress mat [ 333ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.38µs | 0.02% / 0.02% ] dims: 16x2
INFO        │  ┕━ compress mat [ 209ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.04µs | 0.01% / 0.01% ] dims: 4x2
INFO        │  ┕━ compress mat [ 166ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 2.00µs | 0.02% / 0.03% ] dims: 23x8
INFO        │  ┕━ compress mat [ 500ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.79µs | 0.02% / 0.03% ] dims: 16x8
INFO        │  ┕━ compress mat [ 416ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.75µs | 0.02% / 0.02% ] dims: 4x16
INFO        │  ┕━ compress mat [ 541ns | 0.01% ]
INFO        ┝━ reduce matrix quotient [ 1.50µs | 0.02% / 0.02% ] dims: 4x8
INFO        │  ┕━ compress mat [ 333ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 2.04µs | 0.03% / 0.03% ] dims: 48x2
INFO        │  ┕━ compress mat [ 250ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 1.25µs | 0.02% / 0.02% ] dims: 12x2
INFO        │  ┕━ compress mat [ 167ns | 0.00% ]
INFO        ┝━ reduce matrix quotient [ 2.12µs | 0.02% / 0.03% ] dims: 28x8
INFO        │  ┕━ compress mat [ 500ns | 0.01% ]
INFO        ┕━ FRI prover [ 3.45ms | 0.04% / 48.87% ]
INFO           ┝━ commit phase [ 54.0µs | 0.76% / 0.76% ]
INFO           │  ┝━ grind for proof-of-work witness [ 84.0ns | 0.00% ]
INFO           │  ┝━ grind for proof-of-work witness [ 41.0ns | 0.00% ]
INFO           │  ┕━ grind for proof-of-work witness [ 83.0ns | 0.00% ]
INFO           ┝━ grind for proof-of-work witness [ 3.04ms | 43.10% ]
INFO           ┕━ query phase [ 350µs | 4.97% ]
```

</p>
</details> 

Ideally, those inner methods would be at either lower levels or dispatched with identifiers to allow us to better track performance bottlenecks in individual AIRs.

### PR DESCRIPTION
**Pull request by Farukest**
Summary

- Add per-AIR tracing spans (air_idx) in batch-stark prover/verifier loops for better performance analysis
- Lower inner method log levels from INFO to DEBUG to reduce noise at default log level

Changes

Per-AIR identifiers added:
- batch-stark/src/prover.rs - info_span!("compute quotient for AIR", air_idx = i)
- batch-stark/src/verifier.rs - info_span!("verify constraints for AIR", air_idx = i)

Log levels lowered to DEBUG:
- uni-stark: quotient_values, get_log_num_quotient_chunks, get_log_quotient_degree_extension
- fri: evaluate matrix, reduce matrix quotient, compute opened values with Lagrange interpolation
- dft: coset_lde_batch in radix_2_dit_parallel, radix_2_bowers, monty-31

Result

With RUST_LOG=info, logs now show per-AIR spans without repetitive inner method noise. Use RUST_LOG=debug for detailed analysis.

Fixes #1247

### CODE REVIEW

File: fri/src/two_adic_pcs.rs [hunk 1]
```diff
@@ -482,7 +483,7 @@ where
                 izip!(mats.iter(), points.iter(), openings_for_round.iter())
             {
                 let _guard =
-                    info_span!("reduce matrix quotient", dims = %mat.dimensions()).entered();
+                    debug_span!("reduce matrix quotient", dims = %mat.dimensions()).entered();
```
Comment (Nashtare) [inline fri/src/two_adic_pcs.rs:486]: below this, I think it'd be also useful to lower the logging of `compress mat` as it can be quite noisy

```rust
let mat_compressed = debug_span!("compress mat").in_scope(|| {
```

**Review by Nashtare — APPROVED** [review]
Thanks, much clearer!

File: batch-stark/src/prover.rs [hunk 2]
```diff
@@ -258,6 +258,8 @@ where
 
     // TODO: Parallelize this loop for better performance with many instances.
     for (i, trace_domain) in trace_domains.iter().enumerate() {
+        let _air_span = info_span!("compute quotient for AIR", air_idx = i).entered();
```
Comment (Nashtare) [inline batch-stark/src/prover.rs]: below when calling `get_log_num_quotient_chunks`, it may be nice to open a logging scope (same level, info), so that we also get the AIR idx there.

This requires removing `#[instrument(name = "infer log of constraint degree", skip_all)]` at the function definition level.

This would require opening a similar `info_span!("infer log of constraint degree for AIR", air_idx = i).in_scope(|| {...})` on the verifier side too.

**Comment by Farukest** [comment]
@Nashtare applied all your suggestions. thank you. kindly need your check.

**Comment by Nashtare** [comment]
Minor nit @Farukest, while you're fixing formatting, perhaps remove all ` for AIR` in the new logs, as the `air_idx: N` already implies it, making it a tad cleaner.

**Comment by Farukest** [comment]
> Minor nit @Farukest, while you're fixing formatting, perhaps remove all ` for AIR` in the new logs, as the `air_idx: N` already implies it, making it a tad cleaner.

okay I handled that one too. thank you :)
